import type { Profile } from './types'

export const defaultSingleProfile: Profile = {
  name: 'Single Retiree',
  age: 62,
  plan_to_age: 95,
  filing_status: 'single',
  accounts: {
    traditional_ira: 1_000_000,
    roth_ira: 100_000,
    taxable: 1_000_000,
    cash: 100_000,
  },
  income: {
    rental: 0,
    dividends: 10_000,
    pension: 0,
    consulting: 0,
    other_ordinary: 0,
  },
  annual_spending: 1_000_000,
  social_security_claim_age: 70,
  social_security_annual_at_claim: 12_000,
  return_rate: 0.06,
  return_volatility: 0.15,
  inflation_rate: 0.03,
  withdrawal_scheme: 'performance_cola',
  initial_withdrawal_rate: 0.047,
  annual_review_month: 10,
  target_allocation: { stocks: 0.55, bonds: 0.4, cash: 0.05 },
  rebalance_band_pct: 0.02,
}

export const defaultProfile: Profile = {
  name: 'Retired Couple',
  age: 58,
  plan_to_age: 95,
  spouse_age: 62,
  projection_start_year: 2026,
  filing_status: 'mfj',
  accounts: {
    traditional_ira: 1_000_000,
    roth_ira: 100_000,
    taxable: 1_000_000,
    cash: 100_000,
  },
  income: {
    rental: 0,
    dividends: 10_000,
    pension: 0,
    consulting: 0,
    other_ordinary: 0,
  },
  annual_spending: 1_000_000,
  social_security_claim_age: 70,
  social_security_annual_at_claim: 12_000,
  spouse_social_security_annual_at_claim: 0,
  spouse_social_security_claim_age: 70,
  return_rate: 0.06,
  return_volatility: 0.15,
  inflation_rate: 0.03,
  withdrawal_scheme: 'performance_cola',
  initial_withdrawal_rate: 0.047,
  annuity_income_annual: 0,
  annual_review_month: 10,
  performance_skip_cola_after_down_year: true,
  target_allocation: { stocks: 0.55, bonds: 0.4, cash: 0.05 },
  rebalance_band_pct: 0.02,
}
